import a1 from "./assets/a1.jpg";
import a2 from "./assets/a2.jpg";
import c from "./assets/c.jpg";
import d1 from "./assets/d1.jpg";
import d2 from "./assets/d2.jpg";
import d3 from "./assets/d3.jpg";
import c3 from "./assets/c3.jpg";
export const IM = { a1, a2, c, c3, d1, d2, d3 };
export const C = {
  name: "Manthan Jal",
  phone: "+91 7014883800",
  wa: "917014883800",
  email: "dilipsingh.ds585@gmail.com",
  addr: "85, Silicon Town, Near Chaltan, Palsana, Surat, Gujarat, India",
  hours: "Mon–Sat, 10:00 AM – 7:00 PM",
  social: {
    Instagram: [
      "IG",
      "https://www.instagram.com/dilipsinghjadoun?stkn=MW96dGZ4enZ3aGozeg%3D%3D",
    ],
    Facebook: [
      "fB",
      "https://www.facebook.com/dilipsingh.deepak.77?rdid=hQyBYen3wAYd4vSp&share_url=https%3A%2F%2Fwww.facebook.com%2Fshare%2F1CEYHLnZFA%2F#",
    ],
    LinkedIn: [
      "in",
      "https://www.linkedin.com/in/dilip-singh-jadoun-809414138?utm_source=share_via&utm_content=profile&utm_medium=member_android",
    ],
    YouTube: [
      "YT",
      "https://www.youtube.com/@jyotitradingcompany4?si=mcnGxM7kdsv77zzB",
    ],
    WhatsApp: ["WH", "https://wa.me/917014883800"],
  },
};
export const DS = [
  ["Water capacity", "1 litre per minute"],
  ["Size (H × L × W)", "15 × 12 × 6 inch"],
  ["Power supply", "S.M.P.S, 220 V AC input"],
  ["pH range", "8 to 11 pH"],
  ["ORP range", "−100 to −500, as per water"],
  ["Electrolysis", "6 plate, 3 chamber, continuous"],
  ["Plate material", "SS 316L (titanium chamber optional, extra charge)"],
  ["Plate size", "3 × 9 inch"],
  ["Control", "Microcontroller system"],
  ["Safety", "Overload buzzer"],
  ["Filter", "Sponge filter, life as per water"],
];
export const DF = [
  "Four pH modes: 8 drinking, 9 rich H₂O, 10 cooking, 11 veg-wash",
  "Continuous electrolysis with 6 plates in 3 chambers",
  "Microcontroller control with LCD display",
  "Overload buzzer alert",
];
const dom = (id, n, img, tds, pr, d) => ({
  id,
  type: "d",
  name: n,
  img,
  price: pr,
  tds,
  short: d,
  feat: DF,
  spec: [
    ...DS.slice(0, 3),
    ["Applicable TDS", "100 to " + tds + " (input water)"],
    ...DS.slice(3),
  ],
});
export const P = [
  {
    id: "commercial-cmj-60",
    type: "c",
    name: "Commercial Alkaline Water Ionizer CMJ-60",
    img: "c",
    price: 0,
    short:
      "60 LPH stainless steel commercial ionizer with 6 titanium-and-SS316L plates.",
    feat: [
      "60 litres per hour capacity",
      "SS316L + titanium (A-grade certified) plates, 6 plate 3 chamber",
      "Automatic TDS controller, continuous electrolysis",
      "Sponge, CTO and GAC filtration; 2 × 300 GPD membranes",
      "Overload buzzer safety, microcontroller control",
    ],
    spec: [
      ["Model", "CMJ-60"],
      ["Capacity", "60 LPH"],
      ["Voltage", "220 V AC"],
      ["pH", "8.5"],
      ["ORP", "−100 to −500, as per water"],
      ["Applicable TDS", "500 to 1000"],
      ["Plates", "6 plate, 3 chamber"],
      ["Plate material", "SS316L + titanium (A grade) certified"],
      ["Plate size", "9 × 3 inch"],
      ["Control", "Microcontroller system"],
      ["Electrolysis", "Continuous"],
      ["Safety", "Overload buzzer"],
      ["Filters", "Sponge, CTO & GAC (life as per water)"],
      ["Pumps", "DC 24 V (2 nos)"],
      ["Membrane", "300 GPD (2 nos)"],
      ["Body size (W×L×H)", "13 × 18 × 42 inch, ~26 kg"],
      ["Power use", "0.09 per hour (as per brochure)"],
      ["Variants", "Body: ABS or SS. Plates: SS, titanium, platinum-coated"],
      ["Larger models", "250, 500, 1000 LPH and more on request"],
    ],
  },
  {
    id: "commercial-cmj-60-ss",
    type: "c",
    name: "Commercial Alkaline Water Ionizer CMJ-60 (SS Body)",
    img: "c3",
    price: 0,
    short:
      "60 LPH stainless steel commercial ionizer with SS316L + titanium plates.",
    feat: [
      "60 litres per hour capacity",
      "SS316L + titanium (A-grade certified) plates, 6 plate 3 chamber",
      "Automatic TDS controller, continuous electrolysis",
      "Sponge filter, CTO & GAC; 2 × 300 GPD membranes",
      "Overload buzzer safety, microcontroller control",
    ],
    spec: [
      ["Voltage", "220 Input AC"],
      ["pH range", "8.5"],
      ["ORP range", "−100 to −500 as per water"],
      ["Applicable TDS range", "500 to 1000"],
      ["Electrolysis area / plates", "6 plate, 3 chamber"],
      ["Plate material", "SS316L + Titanium (A Grade) certified"],
      ["Plate size", "9 × 3 inch"],
      ["Control method", "Microcontroller system"],
      ["Electrolysis method", "Continuous electrolysis"],
      ["Safety feature", "Overload buzzer"],
      ["Filter type", "Sponge filter, CTO & GAC"],
      ["Filter life", "As per water"],
      ["Pump specification", "DC 24 V (2 nos)"],
      ["Body size (approx)", "13 × 18 × 42 inch (W×L×H)"],
      ["Net weight (approx)", "26 kg"],
      ["Capacity", "60 LPH"],
      ["TDS controller", "Automatic"],
      ["Electricity consumption", "0.09 per hour"],
      ["Membrane", "300 GPD (2 nos)"],
    ],
  },
  {
    id: "domestic-a",
    type: "d",
    name: "Domestic Alkaline Ionizer — White",
    img: "d3",
    price: 120000,
    tds: "300 - 800",
    short: "Compact 1 LPM home ionizer for municipal water up to 300 - 800 TDS.",
    feat: [
      "Four pH modes: 8 drinking, 9 rich H₂O, 10 cooking, 11 veg-wash",
      "Continuous electrolysis with 5 plates ",
      "Microcontroller control with LCD display",
      "Overload buzzer alert",
    ],
    spec: [
      ["Water capacity", "1 litre per minute"],
      ["Size (H × L × W)", "15 × 12 × 6 inch"],
      ["Power supply", "S.M.P.S, 220 V AC input"],
      ["Applicable TDS", "300 to 800 (input water)"],
      ["pH range", "8 to 11 pH"],
      ["ORP range", "−100 to −500, as per water"],
      ["Electrolysis", "5 plate, 3 chamber, continuous"],
      ["Plate material", "ORP-800 (titanium plate, platinum coating optional, extra charge))"],
      ["Plate size", "3 × 9 inch , 3 x 5  inch"],
      ["Control", "Microcontroller system"],
      ["Safety", "Overload buzzer"],
      ["Filter", "Sponge filter, life as per water"],
    ],
  },

  {
    id: "domestic-b",
    type: "d",
    name: "Domestic Alkaline Ionizer — Black Glass",
    img: "d2",
    price: 145000,
    tds: "400 - 900",
    short: "Black glass front, flexible steel spout and four pH modes.",
    feat: [
      "Four pH modes: 8 drinking, 9 rich H₂O, 10 cooking, 11 veg-wash",
      "Continuous electrolysis with 6 plates in 3 chambers",
      "Microcontroller control with LCD display",
      "Overload buzzer alert",
    ],
    spec: [
      ["Water capacity", "1 litre per minute"],
      ["Size (H × L × W)", "15 × 12 × 6 inch"],
      ["Power supply", "S.M.P.S, 220 V AC input"],
      ["Applicable TDS", "100 to 300 (input water)"],
      ["pH range", "8 to 11 pH"],
      ["ORP range", "−400 to −900, as per water"],
      ["Electrolysis", "7 plate, 3 chamber, continuous"],
      ["Plate material", "ORP-800 (titanium plate, platinum coating optional, extra charge))"],
      ["Plate size", "3 × 9 inch , 3 x 5  inch"],
      ["Control", "Microcontroller system"],
      ["Safety", "Overload buzzer"],
      ["Filter", "Sponge filter, life as per water"],
    ],
  },

  {
    id: "domestic-c",
    type: "d",
    name: "Domestic Alkaline Ionizer — Gold",
    img: "d1",
    price: 198000,
    tds: "400 - 1000",
    short: "Handles input water up to 400 -1000 TDS with a clear digital display.",
    feat: [
      "Four pH modes: 8 drinking, 9 rich H₂O, 10 cooking, 11 veg-wash",
      "Continuous electrolysis with 6 plates in 3 chambers",
      "Microcontroller control with LCD display",
      "Overload buzzer alert",
    ],
    spec: [
      ["Water capacity", "1 litre per minute"],
      ["Size (H × L × W)", "15 × 12 × 6 inch"],
      ["Power supply", "S.M.P.S, 220 V AC input"],
      ["Applicable TDS", "400 to 1000 (input water)"],
      ["pH range", "8 to 11 pH"],
      ["ORP range", "−400 to −900, as per water"],
      ["Electrolysis", "9 plate, 3 chamber, continuous"],
      ["Plate material", "ORP-800 (titanium plate, platinum coating optional, extra charge)"],
      ["Plate size", "3 × 9 inch , 3 x 5  inch"],
      ["Control", "Microcontroller system"],
      ["Safety", "Overload buzzer"],
      ["Filter", "Sponge filter, life as per water"],
    ],
  },
];
export const T = {
  en: {
    home: "Home",
    about: "About",
    products: "Products",
    services: "Services",
    atm: "Water ATM",
    benefits: "Benefits",
    contact: "Contact",
    order: "Order Now",
    view: "View Details",
    explore: "Explore Products",
    h1: "Pure water. Advanced ionization. Made in India.",
    h1p: "Alkaline water ionizers for homes, businesses and public places, manufactured in Surat.",
    comm: "Commercial Alkaline Water Ionizer",
    dom: "Domestic Ionizers",
    cfp: "Contact for price",
    mrp: "MRP",
    specs: "Specifications",
    feat: "Key features",
    faq: "FAQ",
    atmT: "Manthan Jal Water ATM",
    atmP: "A self-service alkaline water dispensing kiosk with a touch screen and QR-code payment, made for hotels, streets, campuses and other public places.",
    srv: "Our Services & Benefits",
    ben: "Why Manthan Jal",
    wq: "What makes good water?",
    wqP: "Water quality depends on many parameters, not one number. Check your local drinking-water standard (in India, BIS IS 10500) and get your water tested.",
    cont: "Contact us",
    send: "Send enquiry on WhatsApp",
    call: "Call now",
    name: "Name",
    phone: "Phone",
    city: "City",
    msg: "Message",
    qty: "Quantity",
    addr: "Address",
    prod: "Product",
    place: "Place order on WhatsApp",
    s: [
      ['01 — 1 Year Complete Machine Warranty','02 — 15 Years Plate Warranty','03 — 3 Services Every Year','04 — Customized Plate Options','05 — Expert Installation Support','06 — Technical & Customer Support','07 — Genuine Spare Parts Support']
    ],
    sd: [
      ['Complete machine warranty for 1 year, covering eligible manufacturing defects and product-related issues as per warranty terms.','Up to 15 years warranty on ionizer plates, subject to applicable warranty terms and conditions.','Get 3 scheduled services every year to help maintain your machine and ensure smooth operation.','Choose from 5, 7, and 9 plate configurations based on your requirements. Pricing varies according to the selected plate configuration.','Professional installation assistance to ensure your water ionizer is properly installed and ready to use.','Dedicated assistance for product operation, troubleshooting, and technical queries.','Reliable support for genuine and compatible replacement parts for long-term maintenance.']
    ],
  },
  hi: {
    home: "होम",
    about: "हमारे बारे में",
    products: "उत्पाद",
    services: "सेवाएँ",
    atm: "वाटर ATM",
    benefits: "लाभ",
    contact: "संपर्क",
    order: "अभी ऑर्डर करें",
    view: "विवरण देखें",
    explore: "उत्पाद देखें",
    h1: "शुद्ध जल। उन्नत आयोनाइज़ेशन। मेड इन इंडिया।",
    h1p: "घर, व्यवसाय और सार्वजनिक स्थानों के लिए अल्कलाइन वाटर आयोनाइज़र, सूरत में निर्मित।",
    comm: "कमर्शियल अल्कलाइन वाटर आयोनाइज़र",
    dom: "घरेलू आयोनाइज़र",
    cfp: "कीमत के लिए संपर्क करें",
    mrp: "MRP",
    specs: "विशेषताएँ",
    feat: "मुख्य फीचर्स",
    faq: "अक्सर पूछे जाने वाले प्रश्न",
    atmT: "मंथन जल वाटर ATM",
    atmP: "टच स्क्रीन और QR-कोड पेमेंट वाला सेल्फ-सर्विस अल्कलाइन वाटर डिस्पेंसिंग कियोस्क — होटल, सड़क, कैंपस और सार्वजनिक स्थानों के लिए।",
    srv: "हमारी सेवाएँ और लाभ",
    ben: "मंथन जल क्यों",
    wq: "अच्छा पानी कैसा होता है?",
    wqP: "पानी की गुणवत्ता कई मानकों पर निर्भर करती है, किसी एक संख्या पर नहीं। अपने पानी की जाँच करवाएँ और BIS IS 10500 जैसे मानक देखें।",
    cont: "हमसे संपर्क करें",
    send: "WhatsApp पर पूछताछ भेजें",
    call: "अभी कॉल करें",
    name: "नाम",
    phone: "फ़ोन",
    city: "शहर",
    msg: "संदेश",
    qty: "मात्रा",
    addr: "पता",
    prod: "उत्पाद",
    place: "WhatsApp पर ऑर्डर करें",
    s: [
      '01 — 1 वर्ष की पूरी मशीन वारंटी','02 — 15 वर्ष की प्लेट वारंटी','03 — हर साल 3 सर्विस','04 — कस्टमाइज़ प्लेट विकल्प','05 — एक्सपर्ट इंस्टॉलेशन सपोर्ट','06 — तकनीकी एवं कस्टमर सपोर्ट','07 — जेन्युइन स्पेयर पार्ट्स सपोर्ट'
    ],
    sd: [
      '1 वर्ष की पूरी मशीन वारंटी, वारंटी शर्तों के अनुसार पात्र मैन्युफैक्चरिंग दोषों और उत्पाद संबंधी समस्याओं के लिए।','आयोनाइज़र प्लेटों पर 15 वर्ष तक की वारंटी, लागू वारंटी नियमों और शर्तों के अधीन।','आपकी मशीन को सही रखने और सुचारु संचालन के लिए हर साल 3 निर्धारित सर्विस।','अपनी ज़रूरत के अनुसार 5, 7 और 9 प्लेट कॉन्फ़िगरेशन में से चुनें। कीमत चुने गए प्लेट कॉन्फ़िगरेशन के अनुसार बदलती है।','आपका वाटर आयोनाइज़र सही तरीके से लगे और उपयोग के लिए तैयार हो, इसके लिए प्रोफ़ेशनल इंस्टॉलेशन सहायता।','प्रोडक्ट के संचालन, समस्या समाधान और तकनीकी प्रश्नों के लिए समर्पित सहायता।','लंबे समय के मेंटेनेंस के लिए जेन्युइन और संगत रिप्लेसमेंट पार्ट्स का भरोसेमंद सपोर्ट।'
    ],
  },
};
export const BEN=[
['01 — Advanced Technology','Next-generation water ionization technology designed for efficient and reliable performance.'],
['02 — Premium Plates','Platinum-coated titanium plates with multiple plate configurations to suit different requirements.'],
['03 — Built for Performance','High-quality components and durable construction for long-term use.'],
['04 — Easy Installation','Simple installation and user-friendly operation for a hassle-free experience.'],
['05 — Reliable Support','Dedicated customer support and after-sales assistance whenever you need it.'],
['06 — Pan-India Service','Professional support and service availability across India.'],
];